default:
    before_script:
        - docker info

stages:
    - build
    - test
    - publish
    - deploy

# sast:
#     stage: test

# include:
#     - template: Security/SAST.gitlab-ci.yml

build-job:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    only:
        - main
        - dev
    script:
        - echo "Building the code..."
        - echo "docker build -t ctezlifrn/avaintegrador:$CI_COMMIT_REF_NAME ."
        - echo "Build complete."
# # unit-test-job:
# #     stage: test
# #     script:
# #         - echo "Running unit tests... This will take about 60 seconds."
# #         - sleep 60
# #         - echo "Code coverage is 90%"

# # lint-test-job:
# #     stage: test
# #     script:
# #         - echo "Linting code... This will take about 10 seconds."
# #         - sleep 10
# #         - echo "No lint issues found."

# publish-job:
#     stage: publish
#     only:
#         - main
#         - dev
#     script:
#         - echo "Deploying image..."
#         - echo "docker login -u $DOCKERHUB_REGISTRY_USER -p $DOCKERHUB_REGISTRY_PASSWORD"
#         - echo "docker push ctezlifrn/avaintegrador:$CI_COMMIT_REF_NAME"
#         - echo "Image successfully deployed."

# deploy-job:
#     stage: deploy
#     only:
#         - main
#         - dev
#     script:
#         - echo "Deploying image..."
#         - mkdir -p ~/.ssh
#         - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
#         - chmod 700 ~/.ssh/id_rsa
#         - ssh -o StrictHostKeyChecking=no root@10.126.0.203 "/var/dockers/vai deploy app"
#         - echo "Image successfully deployed."
