services:

  cache:
    image: redis:7.0.2-alpine
    env_file:
      - ./confs/enabled/cache.env
    volumes:
      - "./volumes/cache_data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    env_file:
      - ./confs/enabled/db.env
    volumes:
      # init settings, executed only on deploy
      - "./src/postgres/:/docker-entrypoint-initdb.d"
      # database data
      - "./volumes/db_data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      # confs
      - ./confs/enabled/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/nginx/error_pages:/usr/share/nginx/error_pages
    ports:
      - 80:80
    depends_on:
      - painel
      - ava

  painel:
    image: ctezlifrn/avapainel:1.0.64
    build:
      context: src/python
      # additional_contexts:
      #   django-adminlte3: ../django-adminlte3
    ports:
      - 8000:8000
    env_file:
      - ./confs/enabled/db.env
      - ./confs/enabled/cache.env
      - ./confs/enabled/painel.env
    volumes:
      # - '../django-adminlte3:/apps/django-adminlte3'
      - './src/python:/apps/app'
      - './volumes/painel_media:/var/media'
      - './volumes/painel_static:/var/static'
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
      # healthcheck:
      #   test: ["CMD-SHELL", "curl --silent --fail http://ava/painel/health/ | grep 'Database: OK' || exit 1"]
      #   interval: 3s
      #   timeout: 1s
      #   start_period: 1s
      #   retries: 30

  ava:
    image: ctezlifrn/moodle:moodle4.1.4-php8.1-release002
    # image: ctezlifrn/moodle:moodle4.3.0-php8.2-release003
    # image: registry.gitlab.com/cte-infra/moodle:020
    ports:
      - 8080:80
    env_file:
      - ./confs/enabled/db.env
      - ./confs/enabled/cache.env
      - ./confs/enabled/ava.env
    volumes:
      # Configs
      # - '../moodle__image/src/php/config.php:/var/www/html/config.php'
      - './confs/enabled/extra.ini:/usr/local/etc/php/conf.d/extra.ini'
      # Plugins
      - '../moodle__enrol_suap:/var/www/html/enrol/suap'
      - '../moodle__auth_suap:/var/www/html/auth/suap'
      - '../moodle__local_suap:/var/www/html/local/suap'
      - '../moodle__block_suapattendance:/var/www/html/blocks/suapattendance'
      - '../moodle__theme_moove:/var/www/html/theme/moove'
      - '../moodle__profilefield_json:/var/www/html/user/profile/field/json'
      # Data
      - './volumes/moodle_data:/var/moodledata'
    depends_on:
      db:
        condition: service_healthy
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl --silent --fail http://ava/ | grep AVA_01 || exit 1"
    #     ]
    #   interval: 3s
    #   timeout: 1s
    #   start_period: 1s
    #   retries: 30
